# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: cornix_dongle
    shield: cornix_dongle_eyelash dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: cornix_dongle

  - board: cornix_left
    #shield: cornix_indicator
    artifact-name: cornix_left_default

  - board: cornix_ph_left
    #shield: cornix_indicator
    artifact-name: cornix_left_for_dongle

  - board: cornix_right
    #shield: cornix_indicator
    artifact-name: cornix_right

  - board: cornix_right
    shield: settings_reset
    artifact-name: reset

  - board: seeeduino_xiao_ble
    shield: cornix_yads dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: yads_dongle

  - board: seeeduino_xiao_ble
    shield: cornix_prospector prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: prospector_dongle

  - board: seeeduino_xiao_ble
    shield: cornix_prospector dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DZMK_EXTRA_MODULES_PATH="/github/workspace/zmk-dongle-screen"    
    artifact-name: zmk_dongle_screen

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: dongle_reset
